### PR TITLE
Fixes for touchmove event listener and scrolling

### LINKED ISSUE #141: Chrome Intervention: Unable to preventDefault inside passive event listener due to target being treated as passive.
There is a error in google chrome browser:

```
[Intervention] Unable to preventDefault inside passive event listener
due to target being treated as passive.
```
This happens due to line 221 in Agile.vue 

https://github.com/lukaszflorczak/vue-agile/blob/18f8336215874b310d780675d70c8a30728bc80d/src/Agile.vue#L221

First of all using ```document.ontouchmove``` is quite bad practice, as it is not widely implemented as stated in the note in https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontouchmove

The actual problem is, that the GlobalEventHandlers.ontouchmove is treated as passive and because of that, it cannot call ```preventDefault()```, as explained under options - passive in
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters

"A Boolean which, if true, indicates that the function specified by listener will never call preventDefault(). If a passive listener does call preventDefault(), the user agent will do nothing other than generate a console warning. See Improving scrolling performance with passive listeners to learn more."

So instead you would have to call once:

```js
document.addEventListener("touchmove", somefunction, {passive: false})
```
Within the callback you could than decide to call ```preventDefault()``` on the event, if you want to disable default scrolling. For that you would have to set some variable in the state ...

### PR DESCRIPTION
**Pull request by lukaszflorczak**
Closes #141

### CODE REVIEW

**Comment by alersenkevich** [comment]
> Closes #141


so i checked this out, and seems that is good, swipe now works on mobile correctly

**Comment by alersenkevich** [comment]
but also you need to know that your component have a many problems yet, so i switched the lib for awesome-swiper from chineese people and i enjoy it, although it doesnt work properly on last version, but i can fixed it for 5 minutes and it's easier than fix your case

**Comment by Tragio** [comment]
Hi @lukaszflorczak! Thank you for your amazing work. I would love to know if this will ever be merged and if this is still maintained. Thank you very much!

**Comment by rlam3** [comment]
@lukas-pierce I'm having a problem with lighthouse with this package and event listener. Lighthouse is complaining about the not setting passive into the eventlistener I believe according to: https://stackoverflow.com/questions/47327119/how-to-listen-to-scroll-events-in-vue-nuxtjs

Another reference: https://web.dev/uses-passive-event-listeners/
document.addEventListener('touchstart', onTouchStart, {passive: true});

Screen Shot 2021-05-08 at 7 40 25 AM


Screen Shot 2021-05-08 at 7 40 12 AM

points to
230 - touchstart
232 - touchmove

**Pull request closed without merging**
