### PR TITLE
form component on slide now worked

### PR DESCRIPTION
**Pull request by djvov**
Hello. I use your vue-agile plugin, and I needs to put form inputs on slider. Because of e.preventDefault() in handleMouseDown input fields don't get a focus. I'll remove e.preventDefault()and it is worked. 

Add extension .vue in index.js because webpack gives an error "module has not found"

### CODE REVIEW

**Comment by djvov** [comment]
Can you please help me, explain, plase, what does it mean, "Up to standards"? I just remove 3 lines.

**Comment by lukaszflorczak** [comment]
Hey! Thank you for the PR. I'll test it soon and if everything works properly I'll accept it.

**Comment by djvov** [comment]
> Hey! Thank you for the PR. I'll test it soon and if everything works properly I'll accept it.

hello! please tell me, what I need to do??

**Comment by lukaszflorczak** [comment]
Fixed in `v1.1.0`

**Pull request closed without merging**
